apiVersion: v1
kind: LimitRange
metadata:
  name: video-processing-limits
  namespace: video-processing
  labels:
    app.kubernetes.io/name: video-processor
    app.kubernetes.io/part-of: lago-media-services
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "1"
        memory: 1Gi
        ephemeral-storage: 4Gi
      default:
        cpu: "4"
        memory: 8Gi
        ephemeral-storage: 16Gi
