apiVersion: v1
kind: ResourceQuota
metadata:
  name: video-processing-quota
  namespace: video-processing
  labels:
    app.kubernetes.io/name: video-processor
    app.kubernetes.io/part-of: lago-media-services
spec:
  hard:
    count/jobs.batch: "25"
    count/pods: "25"
    requests.cpu: "16"
    requests.memory: 32Gi
    requests.ephemeral-storage: 64Gi
    limits.cpu: "64"
    limits.memory: 128Gi
    limits.ephemeral-storage: 256Gi
