apiVersion: v1
kind: Secret
metadata:
  name: video-processor-secrets
  namespace: video-processing
  labels:
    app.kubernetes.io/name: video-processor
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: lago-media-services
type: Opaque
stringData:
  VideoAssembly__CallbackBaseUrl: "http://replace-with-main-api-service.replace-with-api-namespace.svc.cluster.local"
  RabbitNotifications__HostName: "replace-with-rabbitmq-service.replace-with-rabbitmq-namespace.svc.cluster.local"
  RabbitNotifications__UserName: "replace-me"
  RabbitNotifications__Password: "replace-me"
