apiVersion: v1
kind: ServiceAccount
metadata:
  name: video-processor
  namespace: video-processing
  labels:
    app.kubernetes.io/name: video-processor
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: lago-media-services
automountServiceAccountToken: false
