<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LagoVista.UserAdmin" />
    <PackageReference Include="LagoVista.Core.Configuration" />
    <PackageReference Include="LagoVista.CloudStorage" />
    <PackageReference Include="KubernetesClient" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LagoVista.MediaServices\LagoVista.MediaServices.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\VideoProcessorJob.yaml" />
  </ItemGroup>
</Project>
