<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LagoVista.UserAdmin" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LagoVista.MediaServices.Models\LagoVista.MediaServices.Models.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\VideoProcessorJob.yaml" />
  </ItemGroup>
</Project>
