<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net9.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>
  <ItemGroup><ProjectReference Include="..\LagoVista.VideoAssembly.Contracts\LagoVista.VideoAssembly.Contracts.csproj" /></ItemGroup>
</Project>
